### ISSUE TITLE
Website is broken on devices with width lower than 960px

### ISSUE THREAD

**Issue by amiria703** [TadavomnisT/TadavomnisT.github.io#1]
Original website now using the property "width: 960px;":
![image](https://github.com/TadavomnisT/TadavomnisT.github.io/assets/54179379/c9bd339c-e6f4-4d7a-a36e-6b8612903495)

Website after changing property to "max-width: 960px;" on mobile:
![image](https://github.com/TadavomnisT/TadavomnisT.github.io/assets/54179379/2978706b-797e-4261-b926-dcf37f486749)

Website after changing property to "max-width: 960px;" on desktop:
![image](https://github.com/TadavomnisT/TadavomnisT.github.io/assets/54179379/23c301a2-2899-4cd1-930b-a52c05a5e00c)

**Comment by TadavomnisT** [comment]
This issue is related to MDEditor: https://github.com/TadavomnisT/MDEditor

Follow this link please:
https://github.com/TadavomnisT/MDEditor/issues/8
